const mongoose = require("mongoose");

const propertySchema = new mongoose.Schema({
  apartment_id: Number,
  project: String,
  location: String,
  property: String,
  num_bedrooms: Number,
  num_bathrooms: Number,
  parking_spaces: Number,
  proximity_to_transport: Number,
  proximity_to_market: Number,
  proximity_to_schools: Number,
  neighborhood_rating: Number,
  year_built: Number,
  security: Number,
  power_backup: Number,
  lift: Number,
  rain_water_harvesting: Number,
  swimming_pool: Number,
  park: Number,
  waste_disposal: Number,
  mini_cinema: Number,
  earthquake_resistance: Number,
  club_house: Number,
  solar_energy: Number,
  event_space: Number,
  gymnasium: Number,
  vaastu_compliant: Number,
  internet_wi_fi_connectivity: Number,
  bar_lounge: Number,
  piped_gas: Number,
  jogging_and_strolling_track: Number,
  grand_entrance_lobby: Number,
  cctv_camera: Number,
  indoor_games_room: Number,
  furnishing: String,
  carpet_area_sqft: Number,
  floor: Number,
  transaction_type: String,
  status: String,
  facing: String,
  address: String,
  current_price: Number,
  registration_charges: Number,
  booking_amount: Number,
  locality_price_Mar23: Number,
  locality_price_Apr23: Number,
  locality_price_May23: Number,
  locality_price_Jun23: Number,
  locality_price_Jul23: Number,
  locality_price_Aug23: Number,
  locality_price_Sept23: Number,
  locality_price_Oct23: Number,
  locality_price_Nov23: Number,
  locality_price_Dec23: Number,
  locality_price_Jan24: Number,
  locality_price_Feb24: Number,
  locality_price_Mar24: Number,
  property_price_Mar23: Number,
  property_price_Apr23: Number,
  property_price_May23: Number,
  property_price_Jun23: Number,
  property_price_Jul23: Number,
  property_price_Aug23: Number,
  property_price_Sept23: Number,
  property_price_Oct23: Number,
  property_price_Nov23: Number,
  property_price_Dec23: Number,
  property_price_Jan24: Number,
  property_price_Feb24: Number,
  property_price_Mar24: Number,
});

const Propertymodel = mongoose.model("Property", propertySchema);

module.exports = Propertymodel;
